language: bash
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - debian-keyring
    - debian-archive-keyring
    - shellcheck
script:
  - shellcheck install
  - shellcheck setup_localhost
  - shellcheck add_domains
  - shellcheck scripts/*
sudo: true
