matrix:
  include:
    allow_failures:
      - os: osx
        osx_image: xcode9.3
    allow_failures:
      - os: osx
        osx_image: xcode9.2
    allow_failures:
      - os: osx
        osx_image: xcode8
    allow_failures:
      - os: osx
        osx_image: xcode6.4
tags:
  - xcode_9-3
  - osx_10-11
# before_install:
#   - xcode-select --install
script:
  - cd tests
  - chmod +x install add_domains scripts/brew_install.sh
  - ./scripts/brew_install.sh 
  - sudo ./install
  - sudo ./add_domains
language: bash
osx_image: xcode9.3
