os: osx
# matrix:
#   include:
#     - os: osx
#       osx_image: xcode9.3
#     - os: osx
#       osx_image: xcode9.2
#     - os: osx
#       osx_image: xcode8
#     - os: osx
#       osx_image: xcode6.4
# before_install:
#   - xcode-select --install
script:
  - cd tests
  - chmod +x brew install add_domains
  - ./brew 
  - sudo ./install
  - sudo ./add_domains
language: bash
osx_image: xcode9.3
