matrix:
  include:
    - os: osx
      osx_image: xcode9.4 # macOS 10.13
    - os: osx
      osx_image: xcode10.3 # macOS 10.14.4
    - os: osx
      osx_image: xcode11.3 # macOS 10.14.6
    - os: osx
      osx_image: xcode11.5 # macOS 10.15.4
before_install:
    - brew install shellcheck
language: shell
script:
    # Run shellcheck on the files.
    - bash -c 'shopt -s globstar nullglob; shellcheck -xa -e SC2154 brew install lamp-add lamp-upgrade scripts/*.sh'
    # Now run specific test cases.
    - cd tests
    - chmod +x install brew lamp-add lamp-upgrade
    - ./brew
    - sudo ./install
    - sudo ./lamp-add
    - sudo ./lamp-upgrade
# after_success: coveralls
