os: osx
matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.2
before_install:
  - brew install shellcheck
script:
  # Run shellcheck on all bash scripts to ensure no errors
  - shellcheck -xa -e SC2154 install brew add_domain scripts/*.sh
  # Now run specific test cases
  - cd tests
  - chmod +x brew install add_domain
  - ./brew 
  - sudo ./install
  - sudo ./add_domain
language: bash
osx_image: xcode9.3
# after_success: coveralls
